Import-Module copy_sqlTables.ps1
$tableNamesRawString = @"
[dbo].[_tmpincdecbalance]
[dbo].[mapping_branch_fix]
[dbo].[Mapping_Employees]
[dbo].[Mapping_EmployeesMap]
[dbo].[Mapping_Inspectionpointtype20140626]
[dbo].[removed_teventprice]
[dbo].[temp_INCDEC_Detail]
[dbo].[temp_INCDEC_Detail_Final]
[dbo].[inv_glsPreDF]
[dbo].[Jody_AGP_auxlist]
[dbo].[OC_InventoryFinal]
[dbo].[OCEmployeeList]
[dbo].[octobervalues]
[dbo].[OctVariableWOupdate]
[dbo].[OrkinAire]
[dbo].[OrkinCA_Branch_Address]
[dbo].[pay_glsPreDF]
[dbo].[ProgramSetupOC]
[dbo].[ProgramSetupOCNC]
[dbo].[Psocid]
[dbo].[StorageFee]
[dbo].[tmpSanofiChanges]
[dbo].[tmpSanofiChanges2]
[dbo].[tmpSanofiChanges3]
[dbo].[tmpWOTargetDeleted]
[dbo].[tOCZenithAccountMap]
[dbo].[tOCZenithInvoiceGroupMap]
[dbo].[tOCZenithSiteMap]
[dbo].[WosToBeSpiltted]
[dbo].[WosToBeSpiltted2]
[dbo].[WosToBeSpiltted3]
[dbo].[WosToBeSpiltted4]
[dbo].[_308Increase]
[dbo].[_Balancing_AccountBalance]
[dbo].[_balancing_baddebtcredits]
[dbo].[_balancing_creditsumbyaccount]
[dbo].[_balancing_invoicesum]
[dbo].[_balancing_invoicesumbyaccount]
[dbo].[_balancing_paymentsreceivedsum]
[dbo].[_balancing_paymentsreceivedsumwithCOP]
[dbo].[_balancing_paymentssumbyaccount]
[dbo].[_balancing_paymentssumbyaccountwithCOP]
[dbo].[_balancing_WOsumbyaccount]
[dbo].[_Balancing_WOValue]
[dbo].[_bkp_tprogrampirollbackrequest]
[dbo].[_bkp_tprogrampirollbackrequestchangehistory]
[dbo].[_DeferredRevenueFocusImport]
[dbo].[_defrev_eventdeferalstoremove]
[dbo].[_defrev_eventprice]
[dbo].[_defrev_eventsrenewalamount]
[dbo].[_defrev_quaraterlyrenewalpaysum]
[dbo].[_defrevenueevents_calcyears]
[dbo].[_DefRevenueProjectionReport]
[dbo].[_defrevenueprojectionreport_maxpaydate]
[dbo].[_DefRevEvents]
[dbo].[_DefRevRenewals]
[dbo].[_HOProjectionForecast]
[dbo].[_renewalPayments]
[dbo].[_renewalPaymentsSum]
[dbo].[_tmp_acquisitionsTable]
[dbo].[_tmp_COPMovements]
[dbo].[_tmpAR]
[dbo].[_tmpglquery]
[dbo].[_tmpmaterial]
[dbo].[_tmpmatused]
[dbo].[_tmpstnsumm]
[dbo].[_tmpsvcs]
[dbo].[_tmptable]
[dbo].[_tmptimeline]
[dbo].[_tmpusagedist]
[dbo].[_tmpwoactvity]
[dbo].[_tprojectionforecast]
[dbo].[AdditionalAccountAnnValue]
[dbo].[aTempService]
[dbo].[aTempServiceNotPaid]
[dbo].[barcodeDups]
[dbo].[CraneEmployeeXref]
[dbo].[CraneMaterials]
[dbo].[craneStationsXref]
[dbo].[CraneStationType]
[dbo].[CWeventdups]
[dbo].[CWUniqueEvents]
[dbo].[DevRev_nov2018]
[dbo].[DupFocusConvServ]
[dbo].[DupWos]
[dbo].[FIX_CARDHOLDERINFO]
[dbo].[FlatRatePricingMethod]
[dbo].[HnHpreserve]
[dbo].[HulettTransfers]
[dbo].[InvoiceWrongProgram]
[dbo].[Mapping_AppMethod]
[dbo].[Mapping_Branch]
[dbo].[Mapping_CancelReason]
[dbo].[Mapping_Credit]
[dbo].[Mapping_Credits]
[dbo].[Mapping_Discounts]
[dbo].[Mapping_Employees20140626]
[dbo].[Mapping_EstimateTypes]
[dbo].[Mapping_InspectionPoint]
[dbo].[Mapping_Materials]
[dbo].[Mapping_Payplans]
[dbo].[Mapping_Propertytype]
[dbo].[Mapping_Route]
[dbo].[Mapping_Routes20140626]
[dbo].[Mapping_ServiceCode]
[dbo].[Mapping_ServiceCode20140626]
[dbo].[Mapping_ServiceName]
[dbo].[Mapping_Sources]
[dbo].[Mapping_Target]
[dbo].[Mapping_TargetPest]
[dbo].[Mapping_TimeOption]
[dbo].[Mapping_Warranty]
[dbo].[Match_CheckBillingAddress]
[dbo].[matchdups]
[dbo].[MATCHSAVE]
[dbo].[OrkinNationals]
[dbo].[PTPRODTC]
[dbo].[RACFinance_TMP]
[dbo].[reconv_services_fix]
[dbo].[RenewalsNotPaid]
[dbo].[RenewalsNotPaidInvoices]
[dbo].[RenewalsNotPaidPayments]
[dbo].[Routes_Excel]
[dbo].[site47028CNStations]
[dbo].[Stg_Conv_ProductNames]
[dbo].[STG_CONV_Services]
[dbo].[Stg_Seasonal_Multi]
[dbo].[TargetPestsXref]
[dbo].[tbl_HOC_monthly_metrics]
[dbo].[Temp_1_WO]
[dbo].[Temp_2_WO]
[dbo].[Temp_4_WO]
[dbo].[Temp_5_WO]
[dbo].[temp_annuals]
[dbo].[temp_ARbyInvoice]
[dbo].[temp_ARbyProgram]
[dbo].[Temp_INCDEC_Summary]
[dbo].[temp_ipptotal]
[dbo].[temp_pprice]
[dbo].[temp_prices]
[dbo].[temp_ServiceTeam]
[dbo].[Temp_TFS104287]
[dbo].[temp_wolabor]
[dbo].[tempebaidtoupdate]
[dbo].[tempHD769928_2]
[dbo].[temployee_emp_int_backup_616]
[dbo].[temployee_emp_int_backup_617]
[dbo].[temppcbacklog_reportall]
[dbo].[tEnhancedBillingHOCTracking]
[dbo].[tfinstatglreport_original]
[dbo].[tmpDeletedCreditCards]
[dbo].[tmpdeviceactivity]
[dbo].[tmpFinstatGlReport_new]
[dbo].[tmpPplanPriceRemoval]
[dbo].[tmpsrv1]
[dbo].[tmpstnsummary]
[dbo].[TmpTBDserv]
[dbo].[tmpTransactionDetailsAR_new]
[dbo].[toremove2017]
[dbo].[tpaymentitemTesting01202012]
[dbo].[WesternMigration_taccountbilling]
[dbo].[WesternMigration_taccountbillingevent]
[dbo].[WesternMigration_taccountbillinghistory]
[dbo].[WesternMigration_taccounteba]
[dbo].[WesternMigration_taccountnote]
[dbo].[WesternMigration_tevent]
[dbo].[WesternMigration_teventprice]
[dbo].[WesternMigration_tprogram]
[dbo].[WesternMigration_tprogramvalue]
[dbo].[ZonesWithStationHistory]
[dbo].[Deleted_tworkorderPendinbservation_HD0000001120218]
"@
[string] $sourceInstance = 'RWbdbagh211'
    [string] $sourceDB = 'prodservsuitedata'
    [string] $destInstance = 'OWFIXDBO203'
    [string] $destDB = 'DatabaseCleanup'
    [bool] $SkipIfTargetTableExists = $true
    [bool] $DropIfTargetTableExists = $false
    [bool] $copyIndexes = $false
    [bool] $copyData = $true
    [string[]] $tables = $tableNamesRawString
    $sourceQueryTimeout =  60
    $bulkCopyBatchSize = 10000
    $bulkCopyTimeout = 120000
 
    $results = Copy-SQLTable `
        -SourceInstance $sourceInstance `
        -SourceDB $sourceDB `
        -DestInstance $destInstance `
        -DestDB $destDB `
        -SkipIfTargetTableExists: $SkipIfTargetTableExists `
        -DropIfTargetTableExists: $DropIfTargetTableExists `
        -CopyIndexes: $copyIndexes `
        -CopyData: $copyData `
        -Tables $tables `
        -SourceQueryTimeout $sourceQueryTimeout `
        -BulkCopyBatchSize $bulkCopyBatchSize `
        -BulkCopyTimeout $bulkCopyTimeout `
        -Verbose
 
    $results |
        Export-Csv -Path "C:\PowerSh\Rollins\TEST.$((Get-Date).ToString('yyyyMMddHHmmss')).csv" -NoTypeInformation
   
    $results |
        ogv