USE [master]
GO

/****** Object:  Database [AG_SEED]    Script Date: 9/18/2021 5:41:38 PM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'AG_SEED')
BEGIN
CREATE DATABASE [AG_SEED]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AG_SEED', FILENAME = N'C:\SQLMounts\Data2\SQLData1\AG_SEED\ag_seed.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AG_SEED_log', FILENAME = N'C:\SQLMounts\Logs2\SQLLogs1\AG_SEED\ag_seed.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
END
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AG_SEED].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AG_SEED] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AG_SEED] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AG_SEED] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AG_SEED] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AG_SEED] SET ARITHABORT OFF 
GO

ALTER DATABASE [AG_SEED] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AG_SEED] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AG_SEED] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AG_SEED] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AG_SEED] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AG_SEED] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AG_SEED] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AG_SEED] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AG_SEED] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AG_SEED] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AG_SEED] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AG_SEED] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AG_SEED] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AG_SEED] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AG_SEED] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AG_SEED] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AG_SEED] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AG_SEED] SET RECOVERY FULL 
GO

ALTER DATABASE [AG_SEED] SET  MULTI_USER 
GO

ALTER DATABASE [AG_SEED] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AG_SEED] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AG_SEED] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AG_SEED] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AG_SEED] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER AUTHORIZATION ON DATABASE::[AG_SEED] TO [ROLLINS\kenneth.parker]
GO

ALTER DATABASE [AG_SEED] SET QUERY_STORE = OFF
GO

GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO [public] AS [dbo]
GO

GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO [public] AS [dbo]
GO

ALTER DATABASE [AG_SEED] SET  READ_WRITE 
GO


USE [AG_SEED]
GO

/****** Object:  Table [dbo].[TASKS_ACTIONS]    Script Date: 9/23/2021 12:55:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TASKS_ACTIONS]') AND type IN (N'U'))
BEGIN
CREATE TABLE [dbo].[TASKS_ACTIONS](
	[STEP_NAME] [VARCHAR](200) NOT NULL,
	[action_dt] [SMALLDATETIME] NOT NULL,
	[COMMENTS] [VARCHAR](1000) NOT NULL
) ON [PRIMARY]
END
GO

ALTER AUTHORIZATION ON [dbo].[TASKS_ACTIONS] TO  SCHEMA OWNER 
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_TASKS_ACTIONS_action_dt]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TASKS_ACTIONS] ADD  CONSTRAINT [DF_TASKS_ACTIONS_action_dt]  DEFAULT (GETDATE()) FOR [action_dt]
END
GO


